name: "Linkux"
mode: "release"
version: "v1.0.1"
port: 8080
start_time: "2021-03-04"
machine_id: 1

auth:
  jwt_expire: 72

log:
  level: "debug"
  filename: "Linkux.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "10.0.224.7"
  port: 3306
  user: "root"
  password: "Cyh123456."
  dbname: "linkux"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: "10.0.96.11"
  port: 6379
  password: "Cyh123456."
  db: 0
  pool_size: 5000
weixin:
  id: "wxeb54c0e66fee4927"
  secret: "cec24107e24419f501691fc694187d84"
  grant_type: "authorization_code"